services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hr
    ports: ["5432:5432"]
    volumes:
      - pgdata:/var/lib/postgresql/data
  api:
    build: .
    env_file: .env
    depends_on: [db]
    ports: ["8000:8000"]
    volumes:
      - ./:/app
volumes:
  pgdata:
